name: Events Demo 1
on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main  #main
      - dev   #dev
      - 'dev-*' # dev-new  or dev-new-this-is
      - 'dev/**' # dev/feet/id   or dev/feet/devs/is
  workflow_dispatch:
  push:
    branches:
      - main  #main
      - dev
      - 'dev-*' # dev-new  or dev-new-this-is
      - 'dev/**' # dev/feet/id   or dev/feet/devs/is
    paths:
      - './src/**' # workflow will get triggered if we push any changes to this path
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."